# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pull-and-run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull hello-world image
        run: docker pull hello-world

      - name: Run hello-world container
        run: docker run hello-world

      - name: Display output
        run: docker logs $(docker ps -q -n1)
